### ISSUE TITLE
RESSARCIMENTO - NOVA SOLICITAÇÃO DE RESSARCIMENTO - CAMPOS DE DATA

### ISSUE THREAD

**Issue by adejota** [Znap-Technologies/nissin-torii-backlog#1]
- [ ] Remover o selecionar e deixar o clique atribuir a data diretamente
- [x] Corrigir o comportamento do tab
- [x] Não permitir datas maiores do que o período atual

**Comment by nfb1patricia** [comment]
- [ok]  Corrigir o comportamento do tab

**Comment by nfb1patricia** [comment]
> * [ ]  Remover o selecionar e deixar o clique atribuir a data diretamente
> * [x]  Corrigir o comportamento do tab
> * [x]  Não permitir datas maiores do que o período atual
>>aplicação permite que o data final seja menor/igual a hoje, entretanto a regra deve considerar o período. ex: 11/2023 data final máxima permitida deve ser 30/11/2023.

errado
<img width="899" alt="image" src="https://github.com/Znap-Technologies/nissin-torii-backlog/assets/154228900/011a34a6-a7c1-43dd-a415-b93481fa8f51">

correto
<img width="895" alt="image" src="https://github.com/Znap-Technologies/nissin-torii-backlog/assets/154228900/810811f8-871a-4833-bbd9-53b8d2bc75e7">
