### ISSUE TITLE
Comprovante

### ISSUE THREAD

**Issue by hugovieiraa** [Znap-Technologies/nissin-torii-backlog#12]
[] adicionar comprovantes 

só é possível adicionar mais de um comprovante se selecionar os comprovantes juntos.
não consegui adicionar um comprovante e depois adicionar outro 

![image](https://github.com/Znap-Technologies/nissin-torii-backlog/assets/153920646/d8d91b88-cbad-4b63-aa1c-df81db9b6eed)

**Comment by hugovieiraa** [comment]
Está solicitando comprovante de pagamento mesmo o comprovante já adicionado

![image](https://github.com/Znap-Technologies/nissin-torii-backlog/assets/153920646/2b30b2ff-c4d0-4104-915a-0518371fd717)

**Comment by hugovieiraa** [comment]
> Está solicitando comprovante de pagamento mesmo o comprovante já adicionado
> 
> ![imagem](https://private-user-images.githubusercontent.com/153920646/291614954-2b30b2ff-c4d0-4104-915a-0518371fd717.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTY0NzQsIm5iZiI6MTcwMjk5NjE3NCwicGF0aCI6Ii8xNTM5MjA2NDYvMjkxNjE0OTU0LTJiMzBiMmZmLWM0ZDAtNDEwNC05MTVhLTA1MTgzNzFmZDcxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxNDI5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzA3YWVhMzZmYTUyMGJmMzZkMmI1MzcxMWM1NmU2ZDI3YTQ5MmY2MDZjMDgzMDc3YmE0NDVhOTdjNDlhYThlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bQ5IIQdbfrjYVHfklWPET0iX-e815zbPR49H9bqiCMo)

só deixou enviar com 1 ação, precisei excluir as demais

**Comment by hugovieiraa** [comment]
Não consigo visualizar o arquivo que foi anexado. 

Com o perfil de Distribuidor/GN/GR.... 

![image](https://github.com/Znap-Technologies/nissin-torii-backlog/assets/153920646/cd74fbad-0f7d-4967-a47c-b5800b940901)

**Comment by nfb1patricia** [comment]
os itens foram corrigidos, pode fechar.
