### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by hugovieiraa** [Znap-Technologies/nissin-torii-backlog#13]
- [x] Diminuir os campos ou a fonte para a opção de "excluir ação" aparecer sem precisar da barra de rolagem 

![image](https://github.com/Znap-Technologies/nissin-torii-backlog/assets/153920646/aa4be769-a324-4361-b95a-ba550515a1c1)

**Comment by hugovieiraa** [comment]
- [ ] clicar em cima do processo e abrir sem precisar selecionar e clicar em editar 
![image](https://github.com/Znap-Technologies/nissin-torii-backlog/assets/153920646/4eff5dec-e383-441d-8765-eb3b305921c5)

**Comment by nfb1patricia** [comment]
itens corrigidos.
