### ISSUE TITLE
Adicionar marketing no fluxo de aprovação

### ISSUE THREAD

**Issue by hugovieiraa** [Znap-Technologies/nissin-torii-backlog#15]
Processo 100/2023 Aprovado 

- [x] Distribuidor
- [x] GN
- [x] GR
- [x] GNV
- [x] GGC
- [x] DIRETOR

Valor 800.000.000,00 50/50

![image](https://github.com/Znap-Technologies/nissin-torii-backlog/assets/153920646/41289c4d-8dab-4c70-872c-7549e01036fe)

**Comment by hugovieiraa** [comment]
- [ ] verificar alçada, após finalizar a aprovação comercial o status foi para "Em aprovação Field Diretoria"
**processo 103/2023**

![image](https://github.com/Znap-Technologies/nissin-torii-backlog/assets/153920646/edaa0546-9c37-4880-aaa6-c51caeec0d4b)

**Comment by hugovieiraa** [comment]
- [ ] enviar acessos das demais áreas para teste de alçada de aprovação 
- [ ] FIELD
- [ ] ACADEMY
- [ ] MARKETING

**Comment by nfb1patricia** [comment]
![image](https://github.com/Znap-Technologies/nissin-torii-backlog/assets/154228900/b41932c4-b143-4a13-99d9-b34ee67f6014)

processo 170/2023
regra de 10% do valor da venda. essa regra não existe.

**Comment by nfb1patricia** [comment]
processo 171/2023
depois de rateada a verba, aplicação se perdeu nos valores e criou novas referências depois da aprovação do GN; alçada de aprovação GR.

<img width="637" alt="image" src="https://github.com/Znap-Technologies/nissin-torii-backlog/assets/154228900/4581e108-7242-4e88-9ac0-be528b17af68">
