### ISSUE TITLE
TROCAS (aguardando validação)

### ISSUE THREAD

**Issue by hugovieiraa** [Znap-Technologies/nissin-torii-backlog#17]
- [x] Todos os itens de trocas devem aparecer em uma única pagina (Deixar padrão de quantidade por pagina como todos) - Dias
- [x] Família "PROMOÇÃO PRODUTOS" não deve estar disponível para trocas - Dias
- [x] Não devem aparecer as colunas Preço total, Preço, Tipo de embalangem e Quantidade por caixa - Dias
- [x] Código do produto a ser considerado é o 010 - Alves
- [x] informação em quantidade por caixa, todas estão com "1", está errado - Dias
- [x] A coluna de SIGLA está sem informação - Dias
- [x] Não deve permitir o envio sem anexo - Alves
- [x] Trazer os ícones para abrir o formulário para o começo da linha, assim como foi feito nos ressarcimentos - Dias
- [x] Para a visualização dos aprovadores, mostrar apenas as linhas que contenham informação digitada pelo distribuidor. (FIXAR BOTÃO REVISAR) - Alves
- [x] Incluir uma soma para evidenciar a quantidade total de pacotes informados - Alves
- [x] Os aprovadores não podem editar o formulário - Dias
- [x] Corrigir anexos assim como foi feito nos ressarcimentos - Alves
- [x] O período das trocas deve respeitar programa no totvs (NAEC102) - Alves

**Comment by nfb1patricia** [comment]
<img width="892" alt="image" src="https://github.com/Znap-Technologies/nissin-torii-backlog/assets/154228900/01a444e6-b05f-406a-9eb7-e4f1a6c7d9ac">

**Comment by nfb1patricia** [comment]
eliminar o campo tabela de preços da tela de trocas

<img width="914" alt="image" src="https://github.com/Znap-Technologies/nissin-torii-backlog/assets/154228900/5ca2bd2d-3375-4ceb-a17c-ef61124f03bf">

**Comment by nfb1patricia** [comment]
MELHORIA: na coluna produto considerar o nome o texto apos a sigla (indicado em amarelo)

<img width="882" alt="image" src="https://github.com/Znap-Technologies/nissin-torii-backlog/assets/154228900/458aba0b-3c92-4339-97e3-eccce32b4ac0">

**Comment by nfb1patricia** [comment]
no arquivo exportado para o excel corrigir as informações:

- [ ] código do produto 09 deve ser alterado para o codigo 10;
- [ ] preço (excluir)
- [ ] quantidade por caixa (excluir)
- [ ] tipo de embalagem (excluir)
- [ ] valor total (excluir)

**Comment by nfb1patricia** [comment]
apos enviado nao deve aparecer a opção "editar solicitação de trocas"

![image](https://github.com/Znap-Technologies/nissin-torii-backlog/assets/154228900/d981d0aa-4680-444f-a066-14bcd5bf16cb)

**Comment by nfb1patricia** [comment]
- [ ] corrigir a função copiar item pois não permite a edição 
- [ ] o sistema não deve permite o envio de mais de um formulário por período.

![image](https://github.com/Znap-Technologies/nissin-torii-backlog/assets/154228900/1de1bed0-ad70-49e4-b2b0-6e977cd403a1)

**Comment by nfb1patricia** [comment]
a aplicação está multiplicando o valor inserido quando o formulário é salvo.
quantidade inserida: milhares (5k, 4k, 3k, 2k, 1k)

![image](https://github.com/Znap-Technologies/nissin-torii-backlog/assets/154228900/4ec93f08-cf89-49ef-bab4-c3430be7f6b0)

**Comment by nfb1patricia** [comment]
- [x] inclusao de comprovante obrigatorio

<img width="901" alt="image" src="https://github.com/Znap-Technologies/nissin-torii-backlog/assets/154228900/54f61377-ff09-4352-8120-80b6037b0fd6">

**Comment by nfb1patricia** [comment]
informação da tela deve ser codigo 10 (pacote)

![image](https://github.com/Znap-Technologies/nissin-torii-backlog/assets/154228900/e5345aa7-f468-486a-9f81-e29d472189eb)
