### ISSUE TITLE
Alterações - Ressarcimento 

### ISSUE THREAD

**Issue by hugovieiraa** [Znap-Technologies/nissin-torii-backlog#37]
- [x] Ocultar coluna > Pagina de listar processo > ID DATA
- [x] Reorganizar Filtros (TODOS OS PERFIS) 
> Numero / Status / Distribuidor / Cliente
> GN / Período / Data
- [x] Incluir código do distribuidor na pagina Cadastro > Equipe de Vendas > GN x Distribuidor

**Comment by hugovieiraa** [comment]
- [ ] Alterar perfis: Hugo, Camila e Bruna como adm

**Comment by hugovieiraa** [comment]
- [ ] ocultar a coluna de "NÍVEL DE APROVAÇÃO" para o perfil de distribuidor

**Comment by nfb1patricia** [comment]
Incluir na lista de ressarcimento o ID da ação do ressarcimento.
