### ISSUE TITLE
CADASTROS - TIPO DE COMPROVANTE - Adicionar coluna de obrigatório

### ISSUE THREAD

**Issue by adejota** [Znap-Technologies/nissin-torii-backlog#4]
- [x] Adicionar coluna de obrigatório
- [x] Validar o comportamento do switch obrigatório ou não

**Comment by Skyrioca** [comment]
validar se ficou correta a entrega

**Comment by nfb1patricia** [comment]
erro: campo % nissin obrigatorio
o campo está preenchido. 

![image](https://github.com/Znap-Technologies/nissin-torii-backlog/assets/154228900/40f719a1-5498-40fd-966d-9834efb70ed2)
