### ISSUE TITLE
RESSARCIMENTO - NOVA SOLICITAÇÃO - Validar a regra de comprovantes obrigatórios

### ISSUE THREAD

**Issue by adejota** [Znap-Technologies/nissin-torii-backlog#5]
- [x] Garantir que o back esteja atualizado com o campo obrigatório no file_type
- [ ] Validar se o campo obrigatório está preenchido e não deixar enviar o formulário sem arquivo

**Comment by nfb1patricia** [comment]
quando mudamos a ação os comprovantes anexados anteriormente são excluidos.
manter pois no input o usuario pode ter se equivocado na alocação da ação, ter que reinserir todos os comprovantes novamente, pode gerar uma demanda desnecessária.

![image](https://github.com/Znap-Technologies/nissin-torii-backlog/assets/154228900/19c8d2ab-1e08-4c80-97f6-a35640b41ee4)

![image](https://github.com/Znap-Technologies/nissin-torii-backlog/assets/154228900/e0b5ab10-73c9-431e-b109-4e0d1b396bfd)
