### ISSUE TITLE
RESSARCIMENTO - NOVA SOLICITAÇÃO - Campo cliente

### ISSUE THREAD

**Issue by adejota** [Znap-Technologies/nissin-torii-backlog#6]
- [ ] Remover a combobox e deixar o campo texto livre
- [ ] Antes de salvar o back deve verificar se já existe igual e utilizar o ID em vez de criar um novo cliente para não duplicar

**Comment by nfb1patricia** [comment]
- [x] combo box foi excluida e o campo agora permite texto livre
- [ ] Antes de salvar o back deve verificar se já existe igual e utilizar o ID em vez de criar um novo cliente para não duplicar (preciso de esclarecimentos sobre esse item).
