### ISSUE TITLE
RESSARCIMENTO - FILTRO DE NÚMERO DO PROCESSO - Alterar de combo para texto livre

### ISSUE THREAD

**Issue by adejota** [Znap-Technologies/nissin-torii-backlog#7]
No primeiro momento:
- [ ] Remover o filtro de Número do processo nas telas abaixo:
- [ ] Listar processos
- [ ] Comprovantes por ressarcimento
- [ ] Ações por ressarcimento
- [ ] Log de aprovações
- [ ] Garantir que a pesquisa do campo "Pesquisar" está filtrando o número do processo corretamente

**Comment by nfb1patricia** [comment]
esse issue não parece fazer sentido
o numero do processo e campo chave e nao deve ser removido das pesquisas.
