### ISSUE TITLE
RESSARCIMENTO - #1 DATA DA AÇÃO

### ISSUE THREAD

**Issue by nfb1patricia** [Znap-Technologies/nissin-torii-backlog#8]
patrícia (15/12): 
passos 3 e 4
data inicial: aplicação permite escolher datas no futuro
data final: aplicação permite selecionar uma data anterior a data do periodo inicial

periodo da ação
a aplicação acusa uma mensagem "a data inicial deve pertencer ao mes seguinte do periodo."
essa mensagem esta equivocada pois a data inicial e final da ação deve ser menor/igual ao periodo e não posterior.

**Comment by nfb1patricia** [comment]
> patrícia (15/12): passos 3 e 4 data inicial: aplicação permite escolher datas no futuro data final: aplicação permite selecionar uma data anterior a data do periodo inicial

> patricia (18/12) a aplicação foi atualizada e já acusa mesngem de "erro". a data inicial deve ser anterior a data final" - OK

**Comment by nfb1patricia** [comment]
a aplicação não permite que a data inicial seja a mesma que a data final - corrigir. podemos ter uma ação que foi realizada em 1 unico dia.

**Comment by nfb1patricia** [comment]
o campo total de caixas não é mais um campo obrigatório.

**Comment by nfb1patricia** [comment]
o campo valor venda R$ está configurado com separador de milhares e sem casas decimais, por favor, alterar para 2 casas decimais depois da virgula.

**Comment by nfb1patricia** [comment]
comprovantes: a aplicação não deve permitir anexar documentos compactados e limitar-se as extensões relacionadas: pdf, doc, docx, xls, xlsx, ppt, pptx e txt

**Comment by nfb1patricia** [comment]
comprovantes
aplicação não reconhece o comprovante inserido "comprovante de pagamento".

**Comment by nfb1patricia** [comment]
tipo de cliente: botão novo e botão lista
o botão lista não funciona, ou seja, não traz qualquer lista de clientes já inseridos/cadastrados.

**Comment by nfb1patricia** [comment]
a aplicação permite que arquivos com mais de 10mb sejam anexados.

**Comment by hugovieiraa** [comment]
Essas são as regras que temos hoje em relação a data: 

![image](https://github.com/Znap-Technologies/nissin-torii-backlog/assets/153920646/54678f25-5947-45ea-a726-75541c518e18)


![image](https://github.com/Znap-Technologies/nissin-torii-backlog/assets/153920646/992a5277-b8f9-498a-bbbc-49c5a6cca558)

**Comment by nfb1patricia** [comment]
> Essas são as regras que temos hoje em relação a data:
> 
> ![image](https://private-user-images.githubusercontent.com/153920646/291694613-54678f25-5947-45ea-a726-75541c518e18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MDg5MTksIm5iZiI6MTcwMzcwODYxOSwicGF0aCI6Ii8xNTM5MjA2NDYvMjkxNjk0NjEzLTU0Njc4ZjI1LTU5NDctNDVlYS1hNzI2LTc1NTQxYzUxOGUxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QyMDIzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMWE4YTRmOTcyZDY3YjM2ZTk4ZmJhZTg3ZGQ1N2EyZmI1ZmQ3NmE1YjcyYjYxZGI0NzhkOWY3NDkwZTIyYmVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WBLxvt5DG1c9mwvURN3d_5lbsUhfMg2B70YJawbHymY)
> 
> ![image](https://private-user-images.githubusercontent.com/153920646/291694538-992a5277-b8f9-498a-bbbc-49c5a6cca558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MDg5MTksIm5iZiI6MTcwMzcwODYxOSwicGF0aCI6Ii8xNTM5MjA2NDYvMjkxNjk0NTM4LTk5MmE1Mjc3LWI4ZjktNDk4YS1iYmJjLTQ5YzVhNmNjYTU1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QyMDIzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmM1MDJjNjM2NGNkMWRiZDVkZjk1YTBlNjM1OTk5N2U5ZjBkMDY5YTg5Yzk2MDZjOTkyZjNiNWNiNzY5NjJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IS4ItVm-uIejp1YJyMstSJlc-uayTiF8ATfYJ0ufhUA)

a aplicação deve respeitar o periodo em aberto e limitar a data final ao ultimo dia do mês.
exemplo:
período: novembro
data final da ação: deve respeitar o limite de >= 30/11/23
data inicial: pode ser igual ou inferior a data final.
